// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShopManager.Models;

#nullable disable

namespace ShopManager.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260613144200_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShopManager.Models.DailyTurnover", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CardAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CashAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ECommerceAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("DailyTurnovers");
                });

            modelBuilder.Entity("ShopManager.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CriticalLimit")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("CurrentQuantity")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CriticalLimit = 3m,
                            CurrentQuantity = 10m,
                            ItemName = "Çilek",
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 2,
                            CriticalLimit = 2m,
                            CurrentQuantity = 8m,
                            ItemName = "Muz",
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 3,
                            CriticalLimit = 2m,
                            CurrentQuantity = 5m,
                            ItemName = "Waffle Hamuru",
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 4,
                            CriticalLimit = 2m,
                            CurrentQuantity = 6m,
                            ItemName = "Dondurma (Çikolata)",
                            Unit = "Litre"
                        },
                        new
                        {
                            Id = 5,
                            CriticalLimit = 2m,
                            CurrentQuantity = 4m,
                            ItemName = "Dondurma (Vanilya)",
                            Unit = "Litre"
                        },
                        new
                        {
                            Id = 6,
                            CriticalLimit = 1m,
                            CurrentQuantity = 2m,
                            ItemName = "Çikolata Sos",
                            Unit = "Litre"
                        },
                        new
                        {
                            Id = 7,
                            CriticalLimit = 50m,
                            CurrentQuantity = 200m,
                            ItemName = "Kağıt Kap (M)",
                            Unit = "Adet"
                        },
                        new
                        {
                            Id = 8,
                            CriticalLimit = 50m,
                            CurrentQuantity = 150m,
                            ItemName = "Kağıt Kap (L)",
                            Unit = "Adet"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
